apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: vae_decoder
    serving.kserve.io/deploymentMode: ModelMesh
  name: vaedecoder
  labels:
    name: vaedecoder
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      runtime: triton-2301
      storage:
        key: aws-connection-my-storage
        path: text-to-image/notebook-output/onnx-redhat-dog/vae_decoder
