apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: unet
    serving.kserve.io/deploymentMode: ModelMesh
  name: unet
  labels:
    name: unet
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      runtime: triton-2301
      storage:
        key: aws-connection-my-storage
        path: text-to-image/custom/onnx-redhat-dog/unet

